"""Average colours of a photo region on a cols×rows grid (for the pixel → dot bridge into Act 9).

python3 scripts/mosaic.py <photo> <x0> <y0> <x1> <y1> <cols> <rows> <out.ts> <exportName>
"""
import sys
from PIL import Image

src = sys.argv[1]
x0, y0, x1, y1, cols, rows = map(float, sys.argv[2:8])
out, name = sys.argv[8], sys.argv[9]
im = Image.open(src).convert('RGB').crop((round(x0), round(y0), round(x1), round(y1)))
small = im.resize((int(cols), int(rows)), Image.BOX)
px = [small.getpixel((x, y)) for y in range(small.height) for x in range(small.width)]
hexes = ['#%02x%02x%02x' % p for p in px]
with open(out, 'w') as f:
    f.write(f'// Generated by scripts/mosaic.py from {src} ({x0:.0f},{y0:.0f})-({x1:.0f},{y1:.0f}), {int(cols)}x{int(rows)} cells.\n')
    f.write(f'export const {name}: string[] = {hexes!r};\n'.replace("'", '"'))
small.save(out.replace('.ts', '.png'))
print('ok', len(hexes))
